
name: Tests

on:
   pull_request:
   # to trigger workflow manually from actions-tab
   workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # set operating systems to test
        os: [ubuntu-latest]
        # set python versions to test
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    name: tests ${{ matrix.os }}  ${{ matrix.python-version }}
    steps:
      # checkout repository
      - uses: actions/checkout@v3
      # install miniconda environment

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: tests/tests_env.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
          create-args: >-
            python=${{ matrix.python-version }}
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pip install -e .[test]
          python -m pytest -v --cov=myst_sphinx_gallery --cov-report=xml
      - name: Upload Image Comparison Artefacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: img_comparison_results
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          env_vars: ${{ matrix.os }}, ${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
